# Generated by Django 4.0 on 2023-05-26 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brevet_database', '0021_alter_personalstatschart_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('ordered', models.DateTimeField(null=True)),
                ('received', models.DateTimeField(null=True)),
                ('removed', models.DateTimeField(null=True)),
                ('cost', models.IntegerField(default=0)),
                ('comment', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('payment', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brevet_database.event')),
                ('randonneur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='brevet_database.randonneur')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
