# Generated by Django 4.0 on 2023-05-26 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brevet_database', '0021_alter_personalstatschart_options'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(choices=[('Медаль', 'Medal')], max_length=64, unique=True)),
                ('price', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Цена',
                'verbose_name_plural': 'Цены',
            },
        ),
        migrations.AlterModelOptions(
            name='medal',
            options={'ordering': ['-active', 'removed', '-event__date'], 'verbose_name': 'Медаль', 'verbose_name_plural': 'Медали'},
        ),
        migrations.AlterField(
            model_name='medal',
            name='cost',
            field=models.IntegerField(default=0, verbose_name='Цена'),
        ),
        migrations.RenameField(
            model_name='medal',
            old_name='cost',
            new_name='price',
        ),
        migrations.AlterField(
            model_name='medal',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Активность'),
        ),
        migrations.AlterField(
            model_name='medal',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='medal',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='medal',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brevet_database.event', verbose_name='Бревет'),
        ),
        migrations.AlterField(
            model_name='medal',
            name='ordered',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Заказано'),
        ),
        migrations.AlterField(
            model_name='medal',
            name='payment',
            field=models.BooleanField(default=False, verbose_name='Оплата'),
        ),
        migrations.AlterField(
            model_name='medal',
            name='randonneur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='brevet_database.randonneur', verbose_name='Рандоннёр'),
        ),
        migrations.AlterField(
            model_name='medal',
            name='received',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Получено'),
        ),
        migrations.AlterField(
            model_name='medal',
            name='removed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Передано'),
        ),
    ]
