# Generated by Django 4.0 on 2023-06-19 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_price_alter_medal_options_remove_medal_cost_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medal',
            options={'ordering': ['-active', '-removed', '-event__date'], 'verbose_name': 'Медаль', 'verbose_name_plural': 'Медали'},
        ),
        migrations.AlterField(
            model_name='price',
            name='item',
            field=models.CharField(choices=[('Medal', 'Медаль'), ('Registration', 'Регистрация'), ('CardN', 'Последние 4 цифры карты ОРВМ')], max_length=64, unique=True, verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='price',
            name='price',
            field=models.IntegerField(verbose_name='Цена'),
        ),
    ]
