# Generated by Django 4.0 on 2023-05-05 04:37
from django.contrib.sites.models import Site
from django.db import migrations

def configure_sites_framework(apps, schema_editor):
    Site.objects.create(domain='brevet.omskvelo.ru', name='brevet.omskvelo.ru')

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '__latest__'),
    ]

    operations = [
        migrations.RunPython(configure_sites_framework),
    ]