FROM nginx:1.21.6-alpine
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx_blue.conf /etc/nginx/conf.d/nginx.conf
COPY nginx_blue.conf /etc/nginx/conf.d
COPY nginx_green.conf /etc/nginx/conf.d

RUN mkdir -p /home/brevet

# Create user and set ownership
RUN addgroup -S  brevet 
RUN adduser -S brevet -G brevet
RUN chown -R brevet:brevet /home/brevet
