# Generated by Django 3.2.8 on 2021-11-26 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ACP_code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('date', models.DateField()),
                ('omskvelo_xref', models.URLField(blank=True)),
                ('external_xref', models.URLField(blank=True)),
                ('club', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='brevet_database.club')),
            ],
        ),
        migrations.CreateModel(
            name='Randonneur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('russian_name', models.CharField(max_length=50)),
                ('russian_surname', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='uploads/img/users/')),
                ('female', models.BooleanField(default=False)),
                ('club', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='brevet_database.club')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('distance', models.IntegerField()),
                ('brm', models.BooleanField(default=True)),
                ('lrm', models.BooleanField(default=False)),
                ('fleche', models.BooleanField(default=False)),
                ('sr600', models.BooleanField(default=False)),
                ('external_xref', models.URLField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='uploads/img/')),
                ('gpx', models.FileField(blank=True, upload_to='uploads/gpx/')),
                ('pdf', models.FileField(blank=True, upload_to='uploads/pdf/')),
                ('club', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, to='brevet_database.club')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homologation', models.CharField(blank=True, max_length=50)),
                ('time', models.DurationField(blank=True)),
                ('success', models.BooleanField(default=True)),
                ('medal', models.BooleanField(default=False)),
                ('comment', models.CharField(blank=True, max_length=200)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brevet_database.event')),
                ('randonneur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brevet_database.randonneur')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='brevet_database.route'),
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('surname', models.CharField(blank=True, max_length=50)),
                ('russian_name', models.CharField(blank=True, max_length=50)),
                ('russian_surname', models.CharField(blank=True, max_length=50)),
                ('female', models.BooleanField(blank=True, default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('club', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, to='brevet_database.club')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brevet_database.event')),
                ('randonneur', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='brevet_database.randonneur')),
            ],
        ),
    ]
