# Generated by Django 4.0 on 2022-01-26 08:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('ACP_code', models.IntegerField(unique=True)),
                ('french_name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('date', models.DateField()),
                ('time', models.TimeField(default=datetime.time(7, 0))),
                ('text_intro', models.TextField(blank=True)),
                ('text', models.TextField(blank=True)),
                ('warning_text', models.TextField(blank=True)),
                ('lights_required', models.BooleanField(default=False)),
                ('responsible', models.CharField(blank=True, max_length=50)),
                ('finished', models.BooleanField(default=False)),
                ('omskvelo_xref', models.URLField(blank=True)),
                ('external_xref', models.URLField(blank=True)),
                ('vk_xref', models.URLField(blank=True)),
                ('club', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='brevet_database.club')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Randonneur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('russian_name', models.CharField(max_length=50)),
                ('russian_surname', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='img/users/')),
                ('female', models.BooleanField(default=False)),
                ('club', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='brevet_database.club')),
            ],
            options={
                'ordering': ['russian_surname'],
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('slug', models.SlugField(blank=True)),
                ('distance', models.IntegerField()),
                ('active', models.BooleanField(default=False)),
                ('controls', models.TextField(blank=True)),
                ('text', models.TextField(blank=True)),
                ('text_brief', models.TextField(blank=True, max_length=120)),
                ('bad_roads', models.BooleanField(default=False)),
                ('brm', models.BooleanField(default=True)),
                ('lrm', models.BooleanField(default=False)),
                ('fleche', models.BooleanField(default=False)),
                ('sr600', models.BooleanField(default=False)),
                ('external_xref', models.URLField(blank=True)),
                ('map_embed_src', models.CharField(blank=True, max_length=500)),
                ('image', models.ImageField(blank=True, upload_to='img/')),
                ('gpx', models.FileField(blank=True, upload_to='gpx/')),
                ('pdf', models.FileField(blank=True, upload_to='pdf/')),
                ('orvm', models.FileField(blank=True, upload_to='orvm/')),
                ('club', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, to='brevet_database.club')),
            ],
            options={
                'ordering': ['-active', 'distance'],
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homologation', models.CharField(blank=True, max_length=50)),
                ('time', models.DurationField(blank=True)),
                ('medal', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brevet_database.event')),
                ('randonneur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brevet_database.randonneur')),
            ],
            options={
                'ordering': ['-event__date'],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='brevet_database.route'),
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('surname', models.CharField(blank=True, max_length=50)),
                ('russian_name', models.CharField(blank=True, max_length=50)),
                ('russian_surname', models.CharField(blank=True, max_length=50)),
                ('female', models.BooleanField(blank=True, default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('club', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, to='brevet_database.club')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brevet_database.event')),
                ('randonneur', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='brevet_database.randonneur')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
