# Generated by Django 4.0 on 2022-02-19 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_randonneur'),
        ('brevet_database', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='club',
        ),
        migrations.RemoveField(
            model_name='application',
            name='female',
        ),
        migrations.RemoveField(
            model_name='application',
            name='name',
        ),
        migrations.RemoveField(
            model_name='application',
            name='randonneur',
        ),
        migrations.RemoveField(
            model_name='application',
            name='russian_name',
        ),
        migrations.RemoveField(
            model_name='application',
            name='russian_surname',
        ),
        migrations.RemoveField(
            model_name='application',
            name='surname',
        ),
        migrations.AddField(
            model_name='application',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
            preserve_default=False,
        ),
    ]
