# Generated by Django 3.2.8 on 2021-12-02 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brevet_database', '0002_event_responsible'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='orvm',
            field=models.FileField(blank=True, upload_to='uploads/orvm/'),
        ),
    ]
