# Generated by Django 4.0 on 2022-05-04 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brevet_database', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='payment',
            field=models.BooleanField(default=False),
        ),
    ]
