# Generated by Django 3.2.8 on 2021-12-03 15:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brevet_database', '0003_route_orvm'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='time',
            field=models.TimeField(default=datetime.time(7, 0)),
        ),
    ]
