# Generated by Django 4.0 on 2022-05-09 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brevet_database', '0003_application_payment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['date', 'otl', 'dnf', 'dsq', 'dns']},
        ),
        migrations.AddField(
            model_name='application',
            name='dns',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='dsq',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='otl',
            field=models.BooleanField(default=False),
        ),
    ]
