# Generated by Django 3.2.8 on 2021-12-05 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brevet_database', '0004_event_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='lights_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='route',
            name='controls',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='route',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
