# Generated by Django 4.0 on 2022-05-23 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brevet_database', '0004_alter_application_options_application_dns_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={},
        ),
        migrations.AddField(
            model_name='event',
            name='fleche_actual_distance',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
