# Generated by Django 4.0 on 2022-05-23 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brevet_database', '0005_alter_application_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='fleche_actual_distance',
        ),
        migrations.AddField(
            model_name='event',
            name='fleche_distance',
            field=models.IntegerField(blank=True, null=True, verbose_name='Actual distance (Fleche only)'),
        ),
    ]
