# Generated by Django 4.0 on 2022-02-24 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brevet_database', '0005_alter_application_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='randonneur',
            name='image',
        ),
    ]
