# Generated by Django 4.0 on 2022-03-17 09:20

import brevet_database.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brevet_database', '0006_remove_randonneur_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='gpx',
            field=models.FileField(blank=True, upload_to=brevet_database.models.gpx_path),
        ),
        migrations.AlterField(
            model_name='route',
            name='image',
            field=models.ImageField(blank=True, upload_to=brevet_database.models.img_path),
        ),
        migrations.AlterField(
            model_name='route',
            name='orvm',
            field=models.FileField(blank=True, upload_to=brevet_database.models.pdf_path),
        ),
        migrations.AlterField(
            model_name='route',
            name='pdf',
            field=models.FileField(blank=True, upload_to=brevet_database.models.pdf_path),
        ),
    ]
