# Generated by Django 3.2.8 on 2021-12-06 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brevet_database', '0006_event_warning_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='vk_xref',
            field=models.URLField(blank=True),
        ),
    ]
