# Generated by Django 3.2.8 on 2021-12-08 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brevet_database', '0007_event_vk_xref'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='randonneur',
            name='image',
            field=models.ImageField(blank=True, upload_to='img/users/'),
        ),
        migrations.AlterField(
            model_name='route',
            name='gpx',
            field=models.FileField(blank=True, upload_to='gpx/'),
        ),
        migrations.AlterField(
            model_name='route',
            name='image',
            field=models.ImageField(blank=True, upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='route',
            name='orvm',
            field=models.FileField(blank=True, upload_to='orvm/'),
        ),
        migrations.AlterField(
            model_name='route',
            name='pdf',
            field=models.FileField(blank=True, upload_to='pdf/'),
        ),
    ]
