# Generated by Django 3.2.8 on 2021-12-08 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brevet_database', '0008_auto_20211208_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='map_embed_src',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
