# Generated by Django 4.0 on 2022-05-26 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brevet_database', '0008_alter_event_payment_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='randonneur',
            name='sr',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
