# Generated by Django 4.0 on 2022-06-17 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brevet_database', '0009_randonneur_sr'),
    ]

    operations = [
        migrations.AddField(
            model_name='randonneur',
            name='total_brevets',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='randonneur',
            name='total_distance',
            field=models.IntegerField(default=0),
        ),
    ]
