# Generated by Django 3.2.8 on 2021-12-09 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brevet_database', '0011_route_bad_roads'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='finished',
            field=models.BooleanField(default=True),
        ),
    ]
