# Generated by Django 3.2.8 on 2021-12-10 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brevet_database', '0012_event_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='thumb',
            field=models.ImageField(blank=True, upload_to='img/thumb/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
