# Generated by Django 4.0 on 2022-09-08 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brevet_database', '0012_club_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='fleche_finish',
            field=models.IntegerField(blank=True, null=True, verbose_name='Actual finish location (Fleche only!)'),
        ),
        migrations.AddField(
            model_name='event',
            name='fleche_name',
            field=models.IntegerField(blank=True, null=True, verbose_name='Fleche name (Fleche only!)'),
        ),
        migrations.AddField(
            model_name='event',
            name='fleche_start',
            field=models.IntegerField(blank=True, null=True, verbose_name='Start location (Fleche only!)'),
        ),
        migrations.AddField(
            model_name='event',
            name='fleche_team',
            field=models.IntegerField(blank=True, null=True, verbose_name='Fleche team name (Fleche only!)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='fleche_distance',
            field=models.IntegerField(blank=True, null=True, verbose_name='Actual distance (Fleche only!)'),
        ),
    ]
