# Generated by Django 3.2.8 on 2021-12-11 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brevet_database', '0013_auto_20211210_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='thumb',
        ),
        migrations.AddField(
            model_name='route',
            name='text_brief',
            field=models.TextField(blank=True),
        ),
    ]
