# Generated by Django 4.0 on 2022-09-08 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brevet_database', '0013_event_fleche_finish_event_fleche_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='fleche_finish',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Actual finish location (Fleche only!)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='fleche_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Fleche name (Fleche only!)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='fleche_start',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Start location (Fleche only!)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='fleche_team',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Fleche team name (Fleche only!)'),
        ),
    ]
