# Generated by Django 3.2.8 on 2021-12-11 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brevet_database', '0014_auto_20211211_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='controls',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='route',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
