# Generated by Django 4.0 on 2022-09-08 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brevet_database', '0014_alter_event_fleche_finish_alter_event_fleche_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='foreign',
            field=models.BooleanField(default=False),
        ),
    ]
