# Generated by Django 3.2.8 on 2021-12-11 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brevet_database', '0015_auto_20211211_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='controls',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='route',
            name='text_brief',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
