# Generated by Django 3.2.8 on 2021-12-11 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brevet_database', '0016_auto_20211211_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='text_brief',
            field=models.TextField(blank=True, max_length=120),
        ),
    ]
