# Generated by Django 3.2.8 on 2021-12-15 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brevet_database', '0018_auto_20211215_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='french_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
