# Generated by Django 4.0 on 2022-11-23 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brevet_database', '0018_clubstatscache'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clubstatscache',
            options={'verbose_name': 'Статистика клуба', 'verbose_name_plural': 'Статистика клуба'},
        ),
    ]
