# Generated by Django 4.0 on 2021-12-17 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brevet_database', '0019_alter_club_french_name'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='randonneur',
            order_with_respect_to='russian_surname',
        ),
    ]
