# Generated by Django 4.0 on 2022-11-24 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brevet_database', '0019_alter_clubstatscache_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalStatsChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.JSONField()),
                ('milestones', models.JSONField()),
                ('randonneur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brevet_database.randonneur')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
