# Generated by Django 4.0 on 2022-11-24 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brevet_database', '0020_personalstatschart'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personalstatschart',
            options={'verbose_name': 'Cтатистика личная (графики)', 'verbose_name_plural': 'Cтатистика личная (графики)'},
        ),
    ]
