# Generated by Django 4.0 on 2021-12-17 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brevet_database', '0020_alter_randonneur_order_with_respect_to'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='randonneur',
            options={'ordering': ['russian_surname']},
        ),
        migrations.AlterOrderWithRespectTo(
            name='randonneur',
            order_with_respect_to=None,
        ),
    ]
