# Generated by Django 4.0 on 2021-12-17 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brevet_database', '0022_alter_event_options_alter_result_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='route',
            options={'ordering': ['-slug', 'distance']},
        ),
    ]
