# Generated by Django 4.0 on 2021-12-17 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brevet_database', '0023_alter_route_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='route',
            options={'ordering': ['active', 'distance']},
        ),
        migrations.AddField(
            model_name='route',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
