# Generated by Django 4.0 on 2022-01-27 08:44

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('brevet_database', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+79999999999', max_length=128, region=None),
        ),
        migrations.AddField(
            model_name='user',
            name='randonneur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='brevet_database.randonneur'),
        ),
    ]
