# Generated by Django 4.0 on 2023-03-05 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_email_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='oauth',
            field=models.BooleanField(default=False),
        ),
    ]
