# Generated by Django 4.0 on 2022-02-11 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brevet_database', '0001_initial'),
        ('users', '0004_user_email_confirmed_alter_user_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_confirmed',
        ),
        migrations.AlterField(
            model_name='user',
            name='randonneur',
            field=models.ForeignKey(default=239, on_delete=django.db.models.deletion.PROTECT, to='brevet_database.randonneur'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_confirmed', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
