# Generated by Django 4.0 on 2022-02-16 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brevet_database', '0001_initial'),
        ('users', '0005_remove_user_email_confirmed_alter_user_randonneur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='randonneur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='brevet_database.randonneur'),
        ),
    ]
