# Generated by Django 4.0 on 2022-02-19 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brevet_database', '0001_initial'),
        ('users', '0006_alter_user_randonneur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='randonneur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='brevet_database.randonneur'),
        ),
    ]
