# Generated by Django 4.0 on 2022-02-24 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brevet_database', '0006_remove_randonneur_image'),
        ('users', '0008_alter_user_randonneur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='randonneur',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='brevet_database.randonneur'),
        ),
    ]
