# Generated by Django 4.0 on 2022-03-17 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brevet_database', '0007_alter_route_gpx_alter_route_image_alter_route_orvm_and_more'),
        ('users', '0009_alter_user_randonneur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='randonneur',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='brevet_database.randonneur'),
        ),
    ]
